In [1]:
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# Prepare dataset
data = np.loadtxt('/content/drive/MyDrive/2022-1학기 DSL 정규세션/[20220210] 앙상블/data.csv', delimiter=',', dtype=float)
labels = data[:, 0]
features = preprocessing.minmax_scale(data[:, 1:])
X_train, X_test, y_train, y_test = train_test_split(features, labels.ravel(), test_size=0.3)

In [4]:
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [5]:
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [6]:
labels

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

### 의사결정나무
* random_state = 2022 으로 설정
* 변수명은 dt_clf 로 설정

In [10]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
# 빈 부분 코드 작성
# decision tree
dt_clf = DecisionTreeClassifier(random_state=2022)

In [26]:
# 개별 분류기에 train set 피팅
clf = dt_clf.fit(X_train, y_train)

In [27]:
# test셋으로 prediction
dt_pred = clf.predict(X_test)

In [28]:
dt_pred

array([0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1.,
       0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
       1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1.,
       1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.])

In [29]:
y_test

array([1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0.,
       1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1.,
       1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0.])

In [38]:
# 성능 확인
# accuracy_score 계산
accuracy_dt = accuracy_score(y_test , dt_pred)
print('의사결정나무 포레스트 정확도: {0:.4f}'.format(accuracy_dt))

의사결정나무 포레스트 정확도: 0.8614


### 랜덤 포레스트
* random_state = 2022
* 변수명 rf_clf 로

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
# random forest
rf_clf = RandomForestClassifier(random_state=2022)

In [33]:
# 개별 분류기에 train set 피팅
rf_clf.fit(X_train , y_train)

RandomForestClassifier(random_state=2022)

In [34]:
# test셋으로 prediction
rf_pred = rf_clf.predict(X_test)

In [36]:
# 성능 확인
# accuracy_score 계산
accuracy = accuracy_score(y_test , rf_pred)
print('랜덤 포레스트 정확도: {0:.4f}'.format(accuracy))

랜덤 포레스트 정확도: 0.9406


### Gradient Boost
* random_state = 2022
* 변수명 gb_clf 로

In [39]:
from sklearn.ensemble import GradientBoostingClassifier

In [40]:
# gradient boost
gb_clf = GradientBoostingClassifier(random_state=2022)

In [41]:
# 개별 분류기에 train set 피팅
gb_clf.fit(X_train , y_train)

GradientBoostingClassifier(random_state=2022)

In [42]:
# test셋으로 prediction
gb_pred =gb_clf.predict(X_test)

In [43]:
# 성능 확인
# accuracy_score 계산
gb_accuracy = accuracy_score(y_test, gb_pred)
print('GBM 정확도: {0:.4f}'.format(gb_accuracy))

GBM 정확도: 0.9208


# 보고서 과제


### 1. voting, bagging, random forest, boosting, adaboost, gradient boost 의 특징 및 장단점을 스스로 정리해보기

voting :  
 서로 다른 알고리즘으로 결정한 여러개의 분류기를 활용하여 다수결의 원칙을 통해 label을 결정함.  soft voting은 확률로, hard voting은 한명당 한표의 투표와 동일한 방식으로 결정한다. 주로 soft voting을 이용한다. 장점은 다양한 알고리즘을 사용하여 결정하므로 다양성 확보가 용이하다는 점이 있다.  
 bagging: 앙상블의 한종류이다. voting과는 달리 서로 같은 알고라즘의 여러개의 분류기를 활용하여 결합하며, 대신 각 분류기마다 random sample을 적용해 다양성을 확보한다. bagging은 bootstrapping aggreagation의 준말로 부트스트랩(복원추출 허용 샘플링)을 통해 만든 샘플들에 대해 모델을 적용하고 그 결과에 대해 평균을 내어 label을 선택한다. 

 random forest:   
 배깅의 한가지 종류로 배깅방식 중 성능이 좋은편이다. 일반적인 배깅은 bootstrapping을 통해 랜덤한 샘플추출로부터 다양성을 확보하지만 샘플을 랜덤 추출하더라도 각각의 분류기가 변수가 중복되므로 비슷한 형태를 띄는 문제가 발생할 수 있다. 즉 tree끼리의 상관성이 높아 충분한 다양성확보가 힘든 상태가 된 것이다. 이를 극복하기 위해 random forest에서는 변수의 임의추출을 통해 추가적으로 다양성을 확보한다. 즉 각 노드를 뿌리 내릴 때 이를 결정하는 변수들의 종류를 임의 추출한다. 이때 주의할 점은 매 노드분류를 할 때마다 하이퍼파라미터로 정해진 수만큼을 결정한다는 점이다. 이를 통해 충분한 다양성을 확보한다.  
 
배깅방식에서는 bootstrapping 데이터를 이용하므로 사용되지 않은 OOB(Out Of Bag)데이터가 존재한다.이를 활용하여 test data를 사용하기 전에 어떤 변수가 중요한지를 확인하는데 사용할 수 있고(체크하고 싶은 변수를 random하게 shuffle하여 무의미한 순서로 만들고 전과후의 에러를 비교해 이 에러가 클 경우 중요한 변수로 판단, 비유를 하자면 중요한 인재가 휴가가면 회사업무가 마비되지만 대충 일하는 사람이 휴가를 가도 사람들이 일하는데 불편함을 못느끼는 것과 같은 이치) 그 결과를 이용해 변수 중요도가 낮은 변수를 제외함으로써 더 나은 모델을 만들 수도 있다. 
 
 boosting:  
  앙상블의 한 종류. 또 다른 앙상블 기법인 배깅과는 달리 "순차적으로" 여러개의 분류기가 학습을 진행한다. 이전 학습에서 잘못 예측한 데이터에 가중치를 주어 오차를 보완해 나가는 방식이며 일반적으로 배깅보다 더 성능이 좋다고 알려져 있다. 그러나 병렬처리가 불가능해 시간이 오래걸린다는 단점이 있다. 크게 Adaboost와 gradient boost로 나뉜다. 

 Adaboost:   
 데이터에 가중치를 부여하며 오차를 보완해나가면서 동시에 모델 자체에도 가중치를 부여하는 모델이다. 즉 특정 분류기가 다른 분류기보다 더 중요한 것을 고려해 가중치를 부여한다. 구체적으로 설명하면 먼저 동일한 weight를 가진 데이터에서 랜덤하게 샘플링을 한 데이터를 통해 각 피처마다 지니계수를 구하고 가장 낮은 지니계수를 가진 분류기를 선택한다.  이 분류기를 통해 나눠진 결과 오분류된 데이터에 높은 가중치를 부여한다. 가중치가 업데이트된 데이터에 대해 또 다시 랜덤하게 샘플을 추출할 때 이전과는 달리 동일한 가중치가 아니므로 높은 가중치를 가진 데이터가 여러번 추출될 확률이 높다. (복원추출 허용임) 이를 통해 아직 제대로 분류되지 않은 데이터에 대해 옳게 분류하는 방향으로 수정이 가능하다. 이러한 과정을 반복하여 여러개의 분류기를 생성하고 최종적으로 각 분류기마다 amount of say를 계산해 이 값이 큰 분류기에 큰 가중치를 부여하여 최종 분류를 결정한다.

 gradient boost:  
  residual fitting을 통해 앞선 분류기가 예측하고 남은 잔차를 이후의 분류기가 다시 예측하는 과정을 순차적으로 반복하는 알고리즘이다. 이를 반복하면서 잔차를 줄여나갈 수 있다. 이때 각 분류기에 대해서 최적 weights를 부여하여 최종결합한다. 또한 최적 weights를 찾을 때 gradient boosting 기법을 활용한다.



### 2. Boosting의 advanced model 인 XGBoost, LightGBM, CatBoost에 대해 찾아보고 정리해보기  
 XGBoost, LightGBM :   
boosting은 병렬처리가 불가능해 시간이 오래 걸린다. 이러한 단점을 보완하기 위해 gradient boosting의 일종이고 bfs방식으로 노드를 내리는 XGboost가 개발되었다. 2년 뒤 이를 더 보완한 dfs방식으로 노드를 내리는 LightGBM(이것도 gradient boosting 계열)이 개발되었지만 당연히 둘다 배깅보다는 훨씬 오래걸린다. (일반적으로 이러한 부스팅의 한계로 인해 시간이 없거나 대략적 분석만 해보려고 할 경우 random forest(배깅의 한종류)를 먼저 해본다.)  
  XGBoost, LightGBM은 성능이 우수하고 일반적인 부스팅보다 시간이 짧게 걸려 많은 data sceintist에게 사랑받는 모델이었으며 실제로 많은 캐글대회 수상자들이 이 모델을 사용했다.

Catboost:  
GBM의 치명적인 문제점 중 하나로 과적합 문제가 존재한다. CatBoost는 이 과적합 문제를 해결하면서 동시에 기존 GBM 계열 알고리즘인 XGBoost, LightGBM 알고리즘보다 학습 속도를 개선하는 장점을 앞세워 개발되었다. 또한 XGBoost, LightGBM이 Hyper-parameter에 따라 성능이 달라지는 문제를 해결하는 것에도 초점을 맞추었다. catBoost를 이용하면 대칭적인 트리 구조를 형성하게 된다. 이를 통해 예측 시간을 감소시킴으로써 기존 Boosting 계열 알고리즘이 느린 학습속도라는 측면에서는 CatBoost 만의 장점이 된다.

