In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data = np.loadtxt('/content/drive/MyDrive/Regular Session Homework/Ensemble/data.csv', delimiter=',', dtype=float)
labels = data[:, 0]
features = preprocessing.minmax_scale(data[:, 1:])
x_train, x_test, y_train, y_test = train_test_split(features, labels.ravel(), test_size=0.3, random_state=2022)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import tree
from sklearn.tree import export_graphviz
!pip install pydot

import pydot
from IPython.core.display import Image 

In [ ]:
clf = tree.DecisionTreeClassifier()
dt_clf = clf.fit(x_train, y_train)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn import metrics
dt_pred = dt_clf.predict(x_test)
confusion_matrix(y_test, dt_pred)
print(confusion_matrix(y_test, dt_pred))
print("Accuracy:", metrics.accuracy_score(y_test,dt_pred))

[[44  6]
 [ 3 48]]
Accuracy: 0.9108910891089109


In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf2 = RandomForestClassifier()
rf_clf = clf2.fit(x_train, y_train)
rf_pred = rf_clf.predict(x_test)
confusion_matrix(y_test, rf_pred)
print(confusion_matrix(y_test, rf_pred))
print("Accuracy:", metrics.accuracy_score(y_test,rf_pred))

[[48  2]
 [ 4 47]]
Accuracy: 0.9405940594059405


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
clf3 = GradientBoostingClassifier()
gb_clf = clf3.fit(x_train, y_train)
gb_pred = gb_clf.predict(x_test)
confusion_matrix(y_test, gb_pred)
print(confusion_matrix(y_test, gb_pred))
print("Accuracy:", metrics.accuracy_score(y_test,gb_pred))

[[49  1]
 [ 3 48]]
Accuracy: 0.9603960396039604
